version: "3"

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_movies
    env_file:
      - db.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: host

  django:
    build:
      context: django
    container_name: django_movies
    env_file:
      - django.env
    volumes:
      - static_volume:/data/static
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    network_mode: host

volumes:
  postgres_volume:
  static_volume:
